# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "ute-beta" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: sudo apt-get update
    - run: sudo apt-get install -y wine64 
    
    - run: npm run build
    - run: ./ci.sh
    - run: npx @electron/packager build --platform win32 --arch x64 --icon './dtabs.ico'
    - run: npx @electron/packager build --platform darwin --arch x64 --icon './dtabs.icns'
    - run: npx @electron/packager build --platform darwin --arch arm64 --icon './dtabs.icns'
    - run: npx @electron/packager build --platform linux --arch x64 --icon './dtabs.ico'
    - run: npx @electron/packager build --platform linux --arch arm64 --icon './dtabs.ico'
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DTabs_windows_x64_${{github.ref_name}}_${{github.sha}}
        path: ./DTabs-win32-x64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DTabs_macos_x64_${{github.ref_name}}_${{github.sha}}
        path: ./DTabs-darwin-x64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DTabs_macos_arm_${{github.ref_name}}_${{github.sha}}
        path: ./DTabs-darwin-arm64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DTabs_linux_x86_${{github.ref_name}}_${{github.sha}}
        path: ./DTabs-linux-x64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DTabs_linux_arm_${{github.ref_name}}_${{github.sha}}
        path: ./DTabs-linux-arm64
        
